### ISSUE TITLE
Options 

### ISSUE THREAD

**Issue by jamestalmage** [DrewML/OctoEdit#15]
I think we should create an options tab. Normally I subscribe to the "sensible defaults" school of thought, but editor config is just too personal. A biggie (I think) is keymap support. People will want to be able to use the same keymaps as their favorite editor.

Really, I think we could have very robust options, especially as it relates to all the addon features. In that case, supporting the "options" is already implemented, we are just creating a UI to configure them:

We could define most of codemirrors options pretty simply: 

``` js
{ 
  name: 'closeTags',
  displayName: 'close tags'
  description: 'automatically close tags'

  // type boolean creates a checkbox
  type: 'boolean',
  default: 'true',

  // the scripts that need to be loaded
  scripts: [
    'codemirror/addons/editor/close-tags.js'
  ],

  // values that need to passed to Codemirror when selected
  injectedOptions: {
    autoCloseTags: true
  }
}
```

**Comment by DrewML** [comment]
Yeah - big fan of this idea, and had it on my mind. I'll start working on the foundation for it tonight.

**Comment by jamestalmage** [comment]
Avoid the `scripts` section of my proposal to start. It will require some pretty complex build steps (splitting everything via browserify, and then selectively loading). We will just bundle everything for now.

In some cases, features are implicitly added when you include the file (`search` for instance), so we will eventually need to work towards a split bundle if we want it to be optional.

**Comment by DrewML** [comment]
Cool. For now, I'm just planning to do the very basics to get the plumbing/UI in place for us to have options in general. After that, we can go to town.

**Comment by DrewML** [comment]
Pushed a commit to master that has an options panel, and a few basic options configured.

![image](https://cloud.githubusercontent.com/assets/5233399/15348379/d0617dda-1c8f-11e6-889c-2f1231e9ac05.png)

@jamestalmage Before I push an update to the Chrome store, want to verify this is working for you locally?

**Comment by jamestalmage** [comment]
👍

**Comment by jamestalmage** [comment]
I don't think the custom tab name is necessary though.

**Comment by DrewML** [comment]
That was mainly there for me to test the `string` type for options, but I suppose there is no harm keeping it. If the configurable options list gets too long it'll be the first to go.

**Comment by sindresorhus** [comment]
I would remove the `Save` button and just save live. That's what we do in GitHub Notifier: https://github.com/sindresorhus/notifier-for-github-chrome/blob/23295fa6c03d29a87907b1bebde43b377ac0f495/extension/options.js#L37 Much better UX.

**Comment by DrewML** [comment]
@sindresorhus Yeah, I had it like that originally last night, and then I got lazy 😆 . Will be doing that soon enough
