### ISSUE TITLE
Theme codemirror to match preview

### ISSUE THREAD

**Issue by jamestalmage** [DrewML/OctoEdit#6]
Not entirely sure how simple it is, but it would be great if we just used the same fonts / highlight colors as GitHub itself. 

Codemirror does have theming capabilities. Not sure what's involved.

**Comment by DrewML** [comment]
Looks like a Theme for CodeMirror is just loading up your own CSS file. [Examples](https://codemirror.net/theme/)

https://codemirror.net/doc/manual.html

> Themes are also simply CSS files, which define colors for various syntactic elements. See the files in the theme directory.

**Comment by DrewML** [comment]
I've got some of this done locally. Can't match 1:1 due to limited classes provided by CodeMirror, but here is what I have:

![image](https://cloud.githubusercontent.com/assets/5233399/15312716/14c9660a-1bcc-11e6-929f-d0868051f938.png)

Thoughts @jamestalmage?

**Comment by jamestalmage** [comment]
👍 - Just the switch to the sans-serif font makes a world of difference.

**Comment by DrewML** [comment]
Closed via 1c940c8

**Comment by jamestalmage** [comment]
@DrewML - This got rid of the default monospaced font. Having monospaced looks better and makes it easier to align things.

**Comment by jamestalmage** [comment]
New:
<img width="129" alt="screenshot 2016-05-17 04 13 14" src="https://cloud.githubusercontent.com/assets/4082216/15315463/c363fab8-1be5-11e6-8522-805b8a6bd2e6.png">

Old:
<img width="137" alt="screenshot 2016-05-17 04 12 53" src="https://cloud.githubusercontent.com/assets/4082216/15315466/c49b0ad4-1be5-11e6-99dc-d5adc8d2e91c.png">

**Comment by DrewML** [comment]
Unfortunately `CodeMirror` doesn't give us any distinct classes that make it super "safe" to style an entire code block separately from the rest of the editor. There are only classes for certain individual values (tokens/vars/properties/etc) that we can style. We _could_ set the `font-family` on each of these, but my fear is that there are values in code they might not add classes too, which would lead to a weird scenario where some things have `monospace` as the font, and some have a serif.

Will test this out a bit later tonight

**Comment by jamestalmage** [comment]
I would say monospace is more important than getting colors right. 

It was super nice not to have to jump back and forth between preview to align things

**Comment by laughedelic** [comment]
Probably it makes sense to replace standard "Write" tab with this codemirror editor with serif font and highlighting and have another one with a monospaced font? Is it doable?

**Comment by DrewML** [comment]
@jamestalmage Pushed an attempted fix for the code fence font to `master`

![image](https://cloud.githubusercontent.com/assets/5233399/15348538/51c538d4-1c91-11e6-9fec-eed3ea851819.png)

@laughedelic Would you mind clarifying? Just want to make 100% sure I'm understanding the ask.

**Comment by jamestalmage** [comment]
Still not monospaced
<img width="59" alt="screenshot 2016-05-18 02 01 45" src="https://cloud.githubusercontent.com/assets/4082216/15348951/c925ef12-1c9c-11e6-9054-4aa581558beb.png">

Both lines have three characters, they should be the same width (they were before theming)

**Comment by DrewML** [comment]
Just pushed a change 
![image](https://cloud.githubusercontent.com/assets/5233399/15349103/c7886358-1c95-11e6-9a62-6653caaa843d.png)
